# PostgreSQL. Versions 9.3 and up are supported.
#
default: &default
  adapter: "postgresql"
  encoding: "unicode"
  database: "<%= ENV.fetch("DB_SCHEMA_NAME") { "hello" } %>"
  username: "<%= ENV.fetch("DB_USERNAME") { "hello" } %>"
  password: "<%= ENV.fetch("DB_PASSWORD") { "password" } %>"
  host: "<%= ENV.fetch("DB_HOST") { "localhost" } %>"
  port: "<%= ENV.fetch("DB_PORT") { 5432 } %>"
  pool: "<%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>"

development:
  <<: *default
  database: <%= ENV.fetch("DB_SCHEMA_NAME") { "hello" } %>_development

test:
  <<: *default
  database: <%= ENV.fetch("DB_SCHEMA_NAME") { "hello" } %>_test

production:
  <<: *default
  database: <%= ENV.fetch("DB_SCHEMA_NAME") { "hello" } %>
  
